### ISSUE TITLE
New line between breaking changes and issues

### ISSUE THREAD

**Issue by btd1337** [martinmcwhorter/commitiquette#12]
Hi @martinmcwhorter could do you see this behavior?

When u insert one breaking change and report one referenced issue commit is generate thus:

```
`BREAKING CHANGE: Example``fix #123`
```

Would be great if could be like that:

```
`BREAKING CHANGE: Example`
`fix #123`
```

**Comment by martinmcwhorter** [comment]
Thanks for the issue. 

This looks good. 
https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers

**Comment by shoichiaizawa** [comment]
I am also trying to test out commitiquette over the [cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) adapter that doesn't support a [selectable scope list](https://github.com/commitizen/cz-conventional-changelog/issues/117). The commitiquette does the job so cool :D

Here is the output of `commitiquette` with every prompt answered:

```
feat(core): add some feature to core

A longer description goes on and on and on and on.
BREAKING CHANGE: The description for the breaking change goes here.Close: #123
```

Other than the missing linebreak of the footer section, based on the Conventional Commits format, there should be a linebreak between the "a longer description" section and the "footer" section.

For instance, here is the output of `cz-conventional-changelog` with every prompt answered:

```
feat(core): add some feature to core

A longer description goes on and on and on and on.

BREAKING CHANGE: The description for the breaking change goes here.

Close: #123
```

**Comment by martinmcwhorter** [comment]
@shoichiaizawa this is great stuff. 

This will get fixed.
