### ISSUE TITLE
Working with lerna

### ISSUE THREAD

**Issue by neviaumi** [martinmcwhorter/commitiquette#2]
**Describe the bug**
When execute `git cz` it show below

**To Reproduce**
Use [@commitlint/config-lerna-scopes](https://www.npmjs.com/package/@commitlint/config-lerna-scopes)
for commit preset and execute `git cz`

**Expected behavior**
When input scope, it should able should list of packages name / can leave it empty

**CommitLint config**
```js
module.exports = { extends: ['@commitlint/config-lerna-scopes'] };
```

**Comment by martinmcwhorter** [comment]
Thanks for the bug report. 

To be clear -- does it list the lerna scopes and not allow you to leave the scope empty? Or does it not list the lerna scopes at all. 

Though I don't use lerna in any projects, I view lerna support as important.

**Comment by neviaumi** [comment]
Sorry i missing attach screenshot
![image](https://user-images.githubusercontent.com/2247500/90266407-84031580-de86-11ea-83c9-c15ca6be7d83.png)

Here is the screenshot

And i find [here](https://github.com/martinmcwhorter/commitiquette/blob/5265d3cec28a6ad5285dd30db7e954f88ad70f0b/src/prompts/scope-maker.ts#L39) is attempt read `rules["scope-enum"]` directly

But [commitlint-config-lerna-scopes](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-lerna-scopes/index.js#L10) `scope-enum` is promise actually

May be this is root cause?

**Comment by neviaumi** [comment]
https://github.com/davidNHK/busybox/tree/demo/commitiquette

Also , I created demo branch in my working repo :) You may take it for testing if needed
