### ISSUE TITLE
Incorrect body-leading-blank rule format

### ISSUE THREAD

**Issue by sebastianquek** [martinmcwhorter/commitiquette#6]
**Describe the bug**
When using the following config, the body does not include a leading blank line.
I was looking at the [source code](https://github.com/martinmcwhorter/commitiquette/blob/master/src/filters.test.ts#L15), am wondering if it should be:
```
test('adds leading blank line', () => {
  const result = leadingBlankFilter('foo', [2, 'always', undefined]);
  expect(result).toBe('\n\nfoo');
});
```

**To Reproduce**
Use commitizen's cli and add a body

**Expected behavior**
Current:
```
feat: new feature
long description body
```

Expected:
```
feat: new feature

long description body
```

For additional context, the output of the default `cz-conventional-changelog` adapter adds an additional line as expected.

**CommitLint config**
```
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "body-leading-blank": [2, "always"],
    "footer-leading-blank": [2, "always"],
  },
};
```

**`package.json`**
```
  "config": {
    "commitizen": {
      "path": "commitiquette"
    }
  },
```

**Comment by martinmcwhorter** [comment]
Needs more investigation. The commit-template should add a preceding newline to the body and footer, giving a blank line.

https://github.com/martinmcwhorter/commitiquette/blob/d48c643c863bc4d743e255f0ec07402835a32a3b/src/commit-template.ts#L32

More tests may be needed to rout out this bug.

**Comment by martinmcwhorter** [comment]
@sebastianquek I am looking at this issue, trying to reproduce it using your steps. I cannot reproduce the issue. 

In the commitlint.config.js I have changed it to:
```javascript
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [2, 'always', ['deps']],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always']
  }
};
```
I follow the commitizen prompts as such:
```
 Select the type of change you're committing:
 chore
? What is the scope of this change:
 :skip
? Write a short, imperative tense description of the change (max 65 chars):
 (11) test config
? Provide a longer description of the change: (press enter to skip, \n for newline)
 
test if config will add leading blank lines
? Are there any breaking changes? No
? Does this fix Does this change affect any open issues? No
```


When VIM comes up to verify my message it reads as:
```
chore: test config
  
test if config will add leading blank lines
```

Can you provide me with the versions of Commitlint and Commitizen you are using? Is it an opensource repository I can look at?

**Comment by sebastianquek** [comment]
I noticed that you've manually entered a newline when providing the longer description. The default commitizen's adapter (cz-conventional-changelog) automatically adds an initial newline instead. You can see an example below.

## Using commitiquette
### package.json
```
  "config": {
    "commitizen": {
      "path": "commitiquette"
    }
  },
```
### Running `git commit`
```
husky > prepare-commit-msg (node v14.4.0)
cz-cli@4.2.2, commitiquette@1.0.9

? Select the type of change you're committing:
 chore
? What is the scope of this change:

? Write a short, imperative tense description of the change (max 93 chars):
 (11) test config
? Provide a longer description of the change: (press enter to skip, \n for newline)
 test if config will add leading blank lines
? Are there any breaking changes? No
? Does this fix Does this change affect any open issues? No
husky > commit-msg (node v14.4.0)
⧗   input: chore: test config

test if config will add leading blank lines
✖   body must have leading blank line [body-leading-blank]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
```
When vim opens, there won't be any blank line:
```
chore: test config
test if config will add leading blank lines
```

## Using cz-conventional-changelog
I've followed [this approach](https://github.com/commitizen/cz-cli#optional-install-and-run-commitizen-locally) to setup commitizen.

### package.json
```
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
```
### Running `git commit`
```
husky > prepare-commit-msg (node v14.4.0)
cz-cli@4.2.2, cz-conventional-changelog@3.3.0

? Select the type of change that you're committing: chore:    Other changes that don't modify src or test files
? What is the scope of this change (e.g. component or file name): (press enter to skip)
? Write a short, imperative tense description of the change (max 93 chars):
 (11) test config
? Provide a longer description of the change: (press enter to skip)
 test if config will add leading blank lines
? Are there any breaking changes? No
? Does this change affect any open issues? No
husky > commit-msg (node v14.4.0)
[chore/conventional-commits 78549633] chore: test config
 1 file changed, 1 insertion(+), 1 deletion(-)
```
In this case, when vim opens, there'll be a blank line:
```
chore: test config

test if config will add leading blank lines
```
---

As an aside, I'm using the following configuration for husky:
```
"husky": {
    "hooks": {
      "prepare-commit-msg": "exec < /dev/tty && git cz --hook || true",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
```

---

**Thanks for looking into this! Happy new year! 🎆**

**Comment by martinmcwhorter** [comment]
No. I did not manually add a new line. The new line was added by
commitiquette after entering the message and pressing enter, enforcing the
rules in the commitlint config.

What version of commitlint are you using?

**Comment by sebastianquek** [comment]
I'm using the following:
"@commitlint/cli": "^11.0.0",
"@commitlint/config-conventional": "^11.0.0",

**Comment by martinmcwhorter** [comment]
Ok. Ill try to repro with these.

**Comment by martinmcwhorter** [comment]
I have been able to reproduce this. I will investigate further on the cause.

**Comment by btd1337** [comment]
The same problem here.

@martinmcwhorter what commitzen packages are you using to this works?

**Comment by jdcmarques** [comment]
Any updates on this?

What version of commitlint and commitizen you were using when you first tested @martinmcwhorter ?

**Comment by martinmcwhorter** [comment]
Should be fixed by https://github.com/martinmcwhorter/commitiquette/pull/8
